### ISSUE TITLE
Configure SAML2 in Dojo

### ISSUE THREAD

**Issue by UilianM** [DefectDojo/Community-Contribs#17]
Hello.

Using deploy in CentOS can I use authentication via SAML2?

I followed this link https://github.com/DefectDojo/Community-Contribs/tree/master/CentOS-7-deploy

How do I enable this in my containers without losing configuration when restarting the service?

**Comment by mtesauro** [comment]
There's loads of ways to setup SAML2 - both from the IDP and DefectDojo side of things so it's really impossible to say exactly how to setup SAML2 in general.  Every SAML2 setup I've seen has been very different.

What you can to is set variables in [env.defectdojo](https://github.com/DefectDojo/Community-Contribs/blob/master/CentOS-7-deploy/dojo/env.defectdojo) and make sure that those variables are passed into the docker-compose.yml file for the uwsgi container like https://github.com/DefectDojo/Community-Contribs/blob/master/CentOS-7-deploy/dojo/docker-compose.yml#L30

There are loads of SAML2 options for DefectDojo - you can find them listed in the settings.py file https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/settings/settings.dist.py#L375

HTH
