### ISSUE TITLE
Need a list of Consultants

### ISSUE THREAD

**Issue by noloader** [DefectDojo/Community-Contribs#24]
Hi Everyone,

I realize this is probably the wrong place to make this suggestion, but we don't know where to find this information... There are no mailing lists to search or discuss issues, and searching the web turns up nearly no information. Even that Slack site provides [no information when searching](https://www.google.com/search?q=defectdojo+site:slack.com). This is an awful situation to put folks in.

Please provide a list of consultants who can assist in installing, configuring and integrating with DefectDojo. For integrating with DefectDojo, we would like someone experienced with Veracode. Other people will have other `<fav tools>`. We are happy to pay someone to help with the tasks.

Thanks in advance.

**Comment by valentijnscholten** [comment]
Our README has a list of maintainers / moderators who can help. There is also the link to our Slack channel which everyone can join to get support our get in touch.

https://github.com/DefectDojo/django-DefectDojo#community-getting-involved-and-updates

**Comment by devGregA** [comment]
Please email info@10security as noted: https://github.com/DefectDojo/django-DefectDojo#commercial-support-and-training
