### ISSUE TITLE
OperationalError: failed to resolve broker hostname

### ISSUE THREAD

**Issue by dkemper01** [DefectDojo/Community-Contribs#31]
Hello and thank you for viewing this issue. I have corrected some minor issues with, and hardened the following CloudFormation template:

    https://github.com/DefectDojo/Community-Contribs/blob/master/aws-deploy-cloudformation-fargate/aws-fargate.yml

I will PR the changes for community review. That said, after having resolved the following issue ...

    https://github.com/DefectDojo/Community-Contribs/issues/27

... authenticating successfully to DefectDojo, and successfully updating a Product I attempted to update a Finding record and was met w/ the following error:

    failed to resolve broker hostname

**Exception Location:** /usr/local/lib/python3.8/site-packages/kombu/connection.py, line 451, in _reraise_as_library_errors
**Python Executable:** /usr/local/bin/uwsgi
**Python Version:** 3.8.12

> OperationalError('failed to resolve broker hostname')
> get_response <bound method BaseHandler._get_response of <<django.core.handlers.wsgi.WSGIHandler object at 0x7f2e3747c0a0>
> request | <WSGIRequest: POST '/finding/128/edit'>

I noticed this issue 
    
    https://github.com/DefectDojo/django-DefectDojo/issues/1422
    
As I highly doubt the exception above is a bug, per-se, what I am wondering is if perhaps there is a misconfiguration in the CloudFormation template I am missing.

**Comment by dkemper01** [comment]
Solved by adding the following environment variable to the uwsgi container definition
```
            - Name: DD_CELERY_BROKER_HOST
               Value: 127.0.0.1
```

**Comment by mtesauro** [comment]
Good find.  This is something that gets fixed 'auto-magically' in compose as Docker networking makes the DNS between the containers 'just work'. 

Thanks for documenting the fix!
