### ISSUE TITLE
How can we suppress known issues in Defectdojo

### ISSUE THREAD

**Issue by bhatisunil2706** [DefectDojo/Community-Contribs#39]
How to suppress a known issue in defectdojo? 
For example If I am running an NMAP scan daily and i want to suppress 80 and 443 open port issues. Is there a way to do that automatically?

**Comment by damiencarol** [comment]
You should check the risk acceptance feature: https://defectdojo.github.io/django-DefectDojo/usage/features/#risk-acceptance
